#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)

BIN_DIR=${AGENTOS_DEV_BIN_DIR:-$ROOT_DIR/bin}
ENV_FILE=${AGENTOS_DEV_ENV_FILE:-$ROOT_DIR/.env.agentos.dev}
GO_CACHE_DIR=${GOCACHE:-$ROOT_DIR/.tmp/go-build}

CHECK_ONLY=0
WITH_TESTS=0
VERIFY_STACK=0
HELP_ONLY=0

usage() {
  cat <<EOF
Usage: $(basename "$0") [--check-only] [--with-tests] [--verify-stack] [--env-file PATH]

Bootstrap a local AgentOS development environment:
  - validate required toolchains
  - warm Go and Rust dependencies
  - build local dev binaries into ./bin
  - generate a sourceable local env file

Options:
  --check-only        Validate prerequisites and write the env file, but skip downloads/builds
  --with-tests        Run Go and Rust tests after building
  --verify-stack      Run scripts/start_full_stack.sh smoke verification after bootstrap
  --env-file PATH     Write the local env file to PATH
  -h, --help          Show this help
EOF
}

log_info() {
  printf '[agentos-dev-setup] %s\n' "$*" >&2
}

log_warn() {
  printf '[agentos-dev-setup] WARN: %s\n' "$*" >&2
}

log_error() {
  printf '[agentos-dev-setup] ERROR: %s\n' "$*" >&2
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --check-only)
        CHECK_ONLY=1
        ;;
      --with-tests)
        WITH_TESTS=1
        ;;
      --verify-stack)
        VERIFY_STACK=1
        ;;
      --env-file)
        [[ $# -ge 2 ]] || {
          log_error "--env-file requires a path"
          return 1
        }
        ENV_FILE=$2
        shift
        ;;
      -h|--help)
        HELP_ONLY=1
        usage
        return 0
        ;;
      *)
        log_error "unknown option: $1"
        usage >&2
        return 1
        ;;
    esac
    shift
  done
}

require_cmd() {
  local cmd=$1
  command -v "$cmd" >/dev/null 2>&1 || {
    log_error "missing required command: $cmd"
    return 1
  }
}

optional_cmd_status() {
  local cmd=$1
  if command -v "$cmd" >/dev/null 2>&1; then
    printf 'present'
  else
    printf 'missing'
  fi
}

check_required_commands() {
  require_cmd go
  require_cmd cargo
  require_cmd curl
  require_cmd python3
}

init_layout() {
  mkdir -p "$BIN_DIR" "$(dirname -- "$ENV_FILE")" "$ROOT_DIR/.tmp" "$GO_CACHE_DIR"
}

warm_dependencies() {
  log_info "downloading Go modules"
  GOCACHE="$GO_CACHE_DIR" go mod download

  log_info "fetching Rust crates"
  (
    cd "$ROOT_DIR/runtime"
    cargo fetch >/dev/null
  )
}

build_binaries() {
  log_info "building Go binaries into $BIN_DIR"
  GOCACHE="$GO_CACHE_DIR" go build -o "$BIN_DIR/controller" ./cmd/controller
  GOCACHE="$GO_CACHE_DIR" go build -o "$BIN_DIR/apiserver" ./cmd/apiserver
  GOCACHE="$GO_CACHE_DIR" go build -o "$BIN_DIR/osctl" ./cmd/osctl
  GOCACHE="$GO_CACHE_DIR" go build -o "$BIN_DIR/claw" ./cmd/claw-cli

  log_info "building Rust worker"
  (
    cd "$ROOT_DIR/runtime"
    cargo build -p agentos-worker >/dev/null
  )

  ln -sf "$ROOT_DIR/runtime/target/debug/agentos-worker" "$BIN_DIR/agentos-worker"
}

write_env_file() {
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup_dev_env.sh
export PATH="$BIN_DIR:\$PATH"
export AGENTOS_MODE=dev
export AGENTOS_RUNTIME=native
export AGENTOS_API_LISTEN_ADDR=127.0.0.1:18080
export AGENTOS_CONTROL_ADDR=127.0.0.1:15052
export AGENTOS_CONTROL_PLANE_ADDR=127.0.0.1:15052
export AGENTOS_WORKER_ADDR=127.0.0.1:15051
export AGENTOS_SERVER_URL=http://127.0.0.1:18080
export AGENTOS_AUTH_TOKEN=dev-token
export AGENTOS_AUTH_PRINCIPAL='dev-user|tenant-dev'
export AGENTOS_STACK_WORKER_ID=local-worker
EOF
}

maybe_run_tests() {
  if [[ "$WITH_TESTS" != "1" ]]; then
    return 0
  fi

  log_info "running Go tests"
  go test ./...

  log_info "running Rust tests"
  (
    cd "$ROOT_DIR/runtime"
    cargo test --workspace
  )
}

maybe_verify_stack() {
  if [[ "$VERIFY_STACK" != "1" ]]; then
    return 0
  fi

  log_info "running full-stack smoke verification"
  bash "$ROOT_DIR/scripts/start_full_stack.sh" --smoke-test --exit-after-smoke
}

print_optional_tool_status() {
  cat <<EOF
Optional tools:
  docker:            $(optional_cmd_status docker)
  protoc:            $(optional_cmd_status protoc)
  protoc-gen-go:     $(optional_cmd_status protoc-gen-go)
  protoc-gen-go-grpc: $(optional_cmd_status protoc-gen-go-grpc)
EOF
}

print_summary() {
  cat <<EOF

AgentOS development environment is ready.

Artifacts:
  bin dir:   $BIN_DIR
  env file:  $ENV_FILE

Next steps:
  source "$ENV_FILE"
  bash scripts/start_full_stack.sh
  bash scripts/start_full_stack.sh --smoke-test --exit-after-smoke
  ./scripts/acceptance.sh

EOF
  print_optional_tool_status
}

main() {
  parse_args "$@"
  if [[ "$HELP_ONLY" == "1" ]]; then
    return 0
  fi

  check_required_commands
  init_layout
  write_env_file

  if [[ "$CHECK_ONLY" != "1" ]]; then
    warm_dependencies
    build_binaries
    maybe_run_tests
    maybe_verify_stack
  else
    log_warn "check-only mode enabled; skipping dependency warm-up and builds"
  fi

  print_summary
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
